services:
  app:
    container_name: rc-sch-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/usr/src/app
      # - /usr/src/app/node_modules  # prevent overwriting node_modules
    env_file:
      - .env.development
    environment:
      NODE_ENV: development
      DATABASE_HOST: db
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:${DATABASE_PORT}/${DATABASE_NAME}?schema=public
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: rc-sch-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - rc-sch-pg-data:/var/lib/postgresql/data

volumes:
  rc-sch-pg-data:
